import React, { useState, useEffect } from 'react';
import {
  Box,
  Paper,
  Typography,
  Grid,
  Card,
  CardContent,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Button,
  Alert,
  CircularProgress
} from '@mui/material';
import {
  BarChart,
  Bar,
  LineChart,
  Line,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer
} from 'recharts';
import { GetApp } from '@mui/icons-material';
import { useAuth } from '../../contexts/AuthContext';
import { apiService } from '../../services/api';
import { type Revenue } from '../../types';
import jsPDF from 'jspdf';

interface ChartData {
  name: string;
  value: number;
}

const ReportsDashboard: React.FC = () => {
  const { user } = useAuth();
  const [reportType, setReportType] = useState('revenue');
  const [timeRange, setTimeRange] = useState('monthly');
  const [revenueData, setRevenueData] = useState<Revenue[]>([]);
  const [machineData, setMachineData] = useState<ChartData[]>([]);
  const [invoiceData, setInvoiceData] = useState<ChartData[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    loadReportData();
  }, [reportType, timeRange]);

  const loadReportData = async () => {
    setLoading(true);
    setError('');
    try {
      const [revenue, machines, invoices] = await Promise.allSettled([
        apiService.getRevenue(),
        apiService.getMachines(),
        apiService.getInvoices()
      ]);

      const revenueResult = revenue.status === 'fulfilled' ? revenue.value : [];
      const machinesData = machines.status === 'fulfilled' ? machines.value : [];
      const invoicesData = invoices.status === 'fulfilled' ? invoices.value : [];

      setRevenueData(revenueResult);
      
      const machineStatusData: ChartData[] = [
        { name: 'Available', value: machinesData.filter((m: any) => m.status === 'AVAILABLE').length },
        { name: 'Rented', value: machinesData.filter((m: any) => m.status === 'RENTED').length },
        { name: 'Maintenance', value: machinesData.filter((m: any) => m.status === 'MAINTENANCE').length }
      ];
      setMachineData(machineStatusData);

      const invoiceStatusData: ChartData[] = [
        { name: 'Paid', value: invoicesData.filter((i: any) => i.status === 'PAID').length },
        { name: 'Pending', value: invoicesData.filter((i: any) => i.status === 'PENDING').length },
        { name: 'Overdue', value: invoicesData.filter((i: any) => i.status === 'OVERDUE').length }
      ];
      setInvoiceData(invoiceStatusData);
    } catch (error) {
      console.error('Error loading report data:', error);
      setError('Failed to load report data. Please check your connection.');
    } finally {
      setLoading(false);
    }
  };

  const generatePDFReport = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(20);
    doc.text('Rental Management Report', 105, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.text(`Generated by: ${user?.name}`, 20, 40);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 50);
    doc.text(`Report Type: ${reportType.toUpperCase()}`, 20, 60);
    
    if (reportType === 'revenue' && revenueData.length > 0) {
      doc.text('Revenue Summary:', 20, 80);
      revenueData.forEach((item, index) => {
        doc.text(`${item.month}: ₹${item.amount}`, 20, 90 + (index * 10));
      });
    } else if (reportType === 'machines' && machineData.length > 0) {
      doc.text('Machine Status Summary:', 20, 80);
      machineData.forEach((item, index) => {
        doc.text(`${item.name}: ${item.value}`, 20, 90 + (index * 10));
      });
    } else if (reportType === 'invoices' && invoiceData.length > 0) {
      doc.text('Invoice Status Summary:', 20, 80);
      invoiceData.forEach((item, index) => {
        doc.text(`${item.name}: ${item.value}`, 20, 90 + (index * 10));
      });
    } else {
      doc.text('No data available for this report type.', 20, 80);
    }
    
    doc.save(`${reportType}-report-${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const COLORS = ['#667eea', '#764ba2', '#f093fb', '#f5576c'];

  const renderChart = () => {
    if (loading) {
      return (
        <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 400 }}>
          <CircularProgress />
        </Box>
      );
    }

    switch (reportType) {
      case 'revenue':
        return revenueData.length > 0 ? (
          <ResponsiveContainer width="100%" height={400}>
            <LineChart data={revenueData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="month" />
              <YAxis />
              <Tooltip formatter={(value) => [`₹${value}`, 'Revenue']} />
              <Line type="monotone" dataKey="amount" stroke="#667eea" strokeWidth={3} />
            </LineChart>
          </ResponsiveContainer>
        ) : (
          <Box sx={{ textAlign: 'center', py: 8 }}>
            <Typography variant="body1" color="text.secondary">
              No revenue data available
            </Typography>
          </Box>
        );
      
      case 'machines':
        return machineData.length > 0 ? (
          <ResponsiveContainer width="100%" height={400}>
            <PieChart>
              <Pie
                data={machineData}
                cx="50%"
                cy="50%"
                labelLine={false}
                label={({ name, percent }) => `${name} ${((percent || 0) * 100).toFixed(0)}%`}
                outerRadius={120}
                fill="#8884d8"
                dataKey="value"
              >
                {machineData.map((_entry, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        ) : (
          <Box sx={{ textAlign: 'center', py: 8 }}>
            <Typography variant="body1" color="text.secondary">
              No machine data available
            </Typography>
          </Box>
        );
      
      case 'invoices':
        return invoiceData.length > 0 ? (
          <ResponsiveContainer width="100%" height={400}>
            <BarChart data={invoiceData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="value" fill="#764ba2" />
            </BarChart>
          </ResponsiveContainer>
        ) : (
          <Box sx={{ textAlign: 'center', py: 8 }}>
            <Typography variant="body1" color="text.secondary">
              No invoice data available
            </Typography>
          </Box>
        );
      
      default:
        return null;
    }
  };

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
          Reports Dashboard
        </Typography>
        <Button
          variant="contained"
          startIcon={<GetApp />}
          onClick={generatePDFReport}
          sx={{
            borderRadius: 2,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          }}
        >
          Export PDF
        </Button>
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{xs:12,md:6}}>
          <FormControl fullWidth>
            <InputLabel>Report Type</InputLabel>
            <Select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
            >
              <MenuItem value="revenue">Revenue Analysis</MenuItem>
              <MenuItem value="machines">Machine Status</MenuItem>
              <MenuItem value="invoices">Invoice Status</MenuItem>
            </Select>
          </FormControl>
        </Grid>
        <Grid size={{xs:12,md:6}}>
          <FormControl fullWidth>
            <InputLabel>Time Range</InputLabel>
            <Select
              value={timeRange}
              onChange={(e) => setTimeRange(e.target.value)}
            >
              <MenuItem value="weekly">Weekly</MenuItem>
              <MenuItem value="monthly">Monthly</MenuItem>
              <MenuItem value="yearly">Yearly</MenuItem>
            </Select>
          </FormControl>
        </Grid>
      </Grid>

      <Paper sx={{ p: 3, borderRadius: 2, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
        <Typography variant="h6" gutterBottom sx={{ fontWeight: 'bold', mb: 2 }}>
          {reportType.charAt(0).toUpperCase() + reportType.slice(1)} Report
        </Typography>
        {renderChart()}
      </Paper>

      <Grid container spacing={3} sx={{ mt: 3 }}>
        <Grid size={{xs:12,md:4}}>
          <Card sx={{ borderRadius: 2, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                Total Revenue
              </Typography>
              <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#667eea' }}>
                ₹{revenueData.reduce((sum, item) => sum + (item.amount || 0), 0).toLocaleString()}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid size={{xs:12,md:4}}>
          <Card sx={{ borderRadius: 2, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                Total Machines
              </Typography>
              <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#764ba2' }}>
                {machineData.reduce((sum, item) => sum + (item.value || 0), 0)}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
        <Grid size={{xs:12,md:4}}>
          <Card sx={{ borderRadius: 2, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
            <CardContent>
              <Typography variant="h6" gutterBottom>
                Total Invoices
              </Typography>
              <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#f5576c' }}>
                {invoiceData.reduce((sum, item) => sum + (item.value || 0), 0)}
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
};

export default ReportsDashboard;