import React, { useState, useEffect } from 'react';
import {
  Box,
  Paper,
  Typography,
  TextField,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Grid,
  Card,
  CardContent,
  Alert,
  CircularProgress,
  Slide,
  Fade,
  Button
} from '@mui/material';
import {
  Search,
  Security,
  Person,
  Assessment,
  GetApp,
  
} from '@mui/icons-material';
import { useAuth } from '../../contexts/AuthContext';
import { apiService } from '../../services/api';
import { type AuditLog, type User } from '../../types';
import jsPDF from 'jspdf';

const AuditLogList: React.FC = () => {
  const { user } = useAuth();
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterAction, setFilterAction] = useState('');
  const [filterEntity, setFilterEntity] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    loadAuditLogs();
    loadUsers();
  }, [user?.id]);

  const loadAuditLogs = async () => {
    setLoading(true);
    setError('');
    try {
      const data = await apiService.getAuditLogs();
      
      // Role-based filtering
      let filteredLogs = data;
      if (user?.role === 'OWNER') {
        // Owner can see logs related to their entities
        filteredLogs = data.filter(log => 
          log.userId === user.id || 
          (log.entityType === 'Machine' && log.details?.includes(user.name)) ||
          (log.entityType === 'Invoice' && log.details?.includes(user.name))
        );
      } else if (user?.role === 'RENTAL') {
        // Rental can only see their own logs
        filteredLogs = data.filter(log => log.userId === user.id);
      }
      
      setAuditLogs(filteredLogs);
    } catch (error) {
      console.error('Error loading audit logs:', error);
      setError('Failed to load audit logs. Please check your connection.');
      setAuditLogs([]);
    } finally {
      setLoading(false);
    }
  };

  const loadUsers = async () => {
    try {
      const data = await apiService.getUsers();
      setUsers(data);
    } catch (error) {
      console.error('Error loading users:', error);
    }
  };

  const generateAuditPDF = () => {
    const doc = new jsPDF();
    let yPosition = 20;

    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('AUDIT LOG REPORT', 105, yPosition, { align: 'center' });
    yPosition += 15;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by: ${user?.name} (${user?.role?.toUpperCase()})`, 20, yPosition);
    yPosition += 8;
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, yPosition);
    yPosition += 15;

    // Summary
    doc.setFont('helvetica', 'bold');
    doc.text('AUDIT SUMMARY:', 20, yPosition);
    yPosition += 8;
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Log Entries: ${auditLogs.length}`, 20, yPosition);
    yPosition += 6;
    doc.text(`Login Actions: ${auditLogs.filter(l => l.actionType === 'LOGIN').length}`, 20, yPosition);
    yPosition += 6;
    doc.text(`Create Actions: ${auditLogs.filter(l => l.actionType === 'CREATE').length}`, 20, yPosition);
    yPosition += 6;
    doc.text(`Update Actions: ${auditLogs.filter(l => l.actionType === 'UPDATE').length}`, 20, yPosition);
    yPosition += 15;

    // Audit logs
    auditLogs.slice(0, 50).forEach((log, index) => {
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${log.action}`, 20, yPosition);
      yPosition += 8;
      
      doc.setFont('helvetica', 'normal');
      doc.text(`User: ${getUserName(log.userId)} | Entity: ${log.entityType}`, 25, yPosition);
      yPosition += 6;
      doc.text(`Date: ${new Date(log.createdAt).toLocaleString()}`, 25, yPosition);
      yPosition += 6;
      if (log.details) {
        const details = doc.splitTextToSize(`Details: ${log.details}`, 160);
        doc.text(details, 25, yPosition);
        yPosition += details.length * 6;
      }
      yPosition += 8;
    });

    const fileName = `audit-log-report-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  };

  const getUserName = (userId?: string) => {
    if (!userId) return 'System';
    const foundUser = users.find(u => u.id === userId);
    return foundUser ? foundUser.name : 'Unknown User';
  };

  const getActionColor = (actionType: AuditLog['actionType']) => {
    switch (actionType) {
      case 'CREATE': return 'success';
      case 'UPDATE': return 'info';
      case 'DELETE': return 'error';
      case 'LOGIN': return 'primary';
      case 'LOGOUT': return 'default';
      case 'EXPORT': return 'warning';
      case 'IMPORT': return 'secondary';
      default: return 'default';
    }
  };

  const getAuditStats = () => {
    const totalLogs = auditLogs.length;
    const loginCount = auditLogs.filter(l => l.actionType === 'LOGIN').length;
    const createCount = auditLogs.filter(l => l.actionType === 'CREATE').length;
    const updateCount = auditLogs.filter(l => l.actionType === 'UPDATE').length;
    const deleteCount = auditLogs.filter(l => l.actionType === 'DELETE').length;

    return { totalLogs, loginCount, createCount, updateCount, deleteCount };
  };

  const stats = getAuditStats();

  const filteredLogs = React.useMemo(() => {
    return auditLogs.filter(log => {
      const matchesSearch = (log.action?.toLowerCase()?.includes(searchTerm.toLowerCase()) || false) ||
                           (log.entityType?.toLowerCase()?.includes(searchTerm.toLowerCase()) || false) ||
                           (getUserName(log.userId)?.toLowerCase()?.includes(searchTerm.toLowerCase()) || false);
      
      const matchesAction = !filterAction || log.actionType?.toLowerCase() === filterAction.toLowerCase();
      const matchesEntity = !filterEntity || log.entityType?.toLowerCase() === filterEntity.toLowerCase();
      
      return matchesSearch && matchesAction && matchesEntity;
    });
  }, [auditLogs, searchTerm, filterAction, filterEntity, users]);

  // Show access restricted message for rental users
  if (user?.role === 'RENTAL') {
    return (
      <Box sx={{ p: 3 }}>
        <Typography variant="h4" sx={{ fontWeight: 'bold', mb: 3 }}>
          Audit Logs
        </Typography>
        <Alert severity="info" icon={<Security />}>
          Access Restricted: Rental users can only view their own activity logs.
        </Alert>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Typography variant="h4" sx={{ fontWeight: 'bold' }}>
          Audit Logs & Security
        </Typography>
        <Button
          variant="outlined"
          startIcon={<GetApp />}
          onClick={generateAuditPDF}
          sx={{ borderRadius: 2 }}
        >
          Export PDF
        </Button>
      </Box>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {/* Stats Cards */}
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{xs:12, sm:6 ,md:2.4}}>
          <Slide direction="up" in timeout={1000}>
            <Card sx={{ borderRadius: 3, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <Box>
                    <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#667eea' }}>
                      {stats.totalLogs}
                    </Typography>
                    <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                      Total Logs
                    </Typography>
                  </Box>
                  <Assessment sx={{ fontSize: 40, color: '#667eea', opacity: 0.7 }} />
                </Box>
              </CardContent>
            </Card>
          </Slide>
        </Grid>
        
        <Grid size={{xs:12, sm:6 ,md:2.4}}>
          <Slide direction="up" in timeout={1200}>
            <Card sx={{ borderRadius: 3, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <Box>
                    <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#2196f3' }}>
                      {stats.loginCount}
                    </Typography>
                    <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                      Logins
                    </Typography>
                  </Box>
                  <Person sx={{ fontSize: 40, color: '#2196f3', opacity: 0.7 }} />
                </Box>
              </CardContent>
            </Card>
          </Slide>
        </Grid>
        
        <Grid size={{xs:12, sm:6 ,md:2.4}}>
          <Slide direction="up" in timeout={1400}>
            <Card sx={{ borderRadius: 3, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <Box>
                    <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#4caf50' }}>
                      {stats.createCount}
                    </Typography>
                    <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                      Creates
                    </Typography>
                  </Box>
                  <Assessment sx={{ fontSize: 40, color: '#4caf50', opacity: 0.7 }} />
                </Box>
              </CardContent>
            </Card>
          </Slide>
        </Grid>
        
        <Grid size={{xs:12, sm:6 ,md:2.4}}>
          <Slide direction="up" in timeout={1600}>
            <Card sx={{ borderRadius: 3, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <Box>
                    <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#ff9800' }}>
                      {stats.updateCount}
                    </Typography>
                    <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                      Updates
                    </Typography>
                  </Box>
                  <Assessment sx={{ fontSize: 40, color: '#ff9800', opacity: 0.7 }} />
                </Box>
              </CardContent>
            </Card>
          </Slide>
        </Grid>
        
        <Grid size={{xs:12, sm:6 ,md:2.4}}>
          <Slide direction="up" in timeout={1800}>
            <Card sx={{ borderRadius: 3, boxShadow: '0 4px 20px rgba(0,0,0,0.1)' }}>
              <CardContent>
                <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <Box>
                    <Typography variant="h4" sx={{ fontWeight: 'bold', color: '#f44336' }}>
                      {stats.deleteCount}
                    </Typography>
                    <Typography variant="body2" sx={{ color: 'text.secondary' }}>
                      Deletes
                    </Typography>
                  </Box>
                  <Assessment sx={{ fontSize: 40, color: '#f44336', opacity: 0.7 }} />
                </Box>
              </CardContent>
            </Card>
          </Slide>
        </Grid>
      </Grid>

      {/* Filters */}
      <Fade in timeout={2000}>
        <Paper sx={{ p: 2, mb: 3, borderRadius: 2 }}>
          <Grid container spacing={2} alignItems="center">
            <Grid size={{xs:12, md:6}}>
              <TextField
                fullWidth
                placeholder="Search audit logs..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                InputProps={{
                  startAdornment: <Search sx={{ mr: 1, color: 'text.secondary' }} />
                }}
              />
            </Grid>
            <Grid size={{xs:12, md:3}}>
              <FormControl fullWidth>
                <InputLabel>Filter by Action</InputLabel>
                <Select
                  value={filterAction}
                  onChange={(e) => setFilterAction(e.target.value)}
                >
                  <MenuItem value="">All Actions</MenuItem>
                  <MenuItem value="LOGIN">Login</MenuItem>
                  <MenuItem value="logout">Logout</MenuItem>
                  <MenuItem value="create">Create</MenuItem>
                  <MenuItem value="update">Update</MenuItem>
                  <MenuItem value="delete">Delete</MenuItem>
                  <MenuItem value="export">Export</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid size={{xs:12, md:3}}>
              <FormControl fullWidth>
                <InputLabel>Filter by Entity</InputLabel>
                <Select
                  value={filterEntity}
                  onChange={(e) => setFilterEntity(e.target.value)}
                >
                  <MenuItem value="">All Entities</MenuItem>
                  <MenuItem value="User">User</MenuItem>
                  <MenuItem value="Machine">Machine</MenuItem>
                  <MenuItem value="Invoice">Invoice</MenuItem>
                  <MenuItem value="Contract">Contract</MenuItem>
                  <MenuItem value="Ticket">Ticket</MenuItem>
                </Select>
              </FormControl>
            </Grid>
          </Grid>
        </Paper>
      </Fade>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 200 }}>
          <CircularProgress size={60} />
        </Box>
      ) : (
        <TableContainer component={Paper} sx={{ borderRadius: 2 }}>
          <Table>
            <TableHead>
              <TableRow sx={{ backgroundColor: '#f5f5f5' }}>
                <TableCell sx={{ fontWeight: 'bold' }}>Timestamp</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>User</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>Action</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>Entity Type</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>Entity ID</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>Action Type</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>IP Address</TableCell>
                <TableCell sx={{ fontWeight: 'bold' }}>Details</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {filteredLogs.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={8} sx={{ textAlign: 'center', py: 4 }}>
                    <Typography variant="body1" color="text.secondary">
                      {searchTerm || filterAction || filterEntity ? 'No audit logs found matching your filters.' : 'No audit logs available.'}
                    </Typography>
                  </TableCell>
                </TableRow>
              ) : (
                filteredLogs.map((log) => (
                  <TableRow key={log.id} hover>
                    <TableCell>
                      <Typography variant="body2">
                        {new Date(log.createdAt).toLocaleString()}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <Person sx={{ color: 'text.secondary', fontSize: 16 }} />
                        {getUserName(log.userId)}
                      </Box>
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" sx={{ fontWeight: 'bold' }}>
                        {log.action}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Chip
                        label={log.entityType}
                        variant="outlined"
                        size="small"
                        color="primary"
                      />
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" sx={{ fontFamily: 'monospace' }}>
                        {log.entityId || 'N/A'}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Chip
                        label={log.actionType.toUpperCase()}
                        color={getActionColor(log.actionType)}
                        size="small"
                      />
                    </TableCell>
                    <TableCell>
                      <Typography variant="body2" sx={{ fontFamily: 'monospace', fontSize: '0.75rem' }}>
                        {log.ipAddress || 'N/A'}
                      </Typography>
                    </TableCell>
                    <TableCell>
                      <Typography 
                        variant="body2" 
                        sx={{ 
                          maxWidth: 200, 
                          overflow: 'hidden', 
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap'
                        }}
                        title={log.details}
                      >
                        {log.details || 'No details'}
                      </Typography>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </TableContainer>
      )}
    </Box>
  );
};

export default AuditLogList;