import jsPDF from 'jspdf';
import { type Invoice, type Machine, type User, type Contract, type RentalRequest } from '../../types';

export const generateInvoicePDF = (invoice: Invoice): void => {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(20);
  pdf.setTextColor(25, 118, 210);
  pdf.text('XEROX RENTAL INVOICE', 20, 30);
  
  // Invoice details
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Invoice Number: ${invoice.invoiceNumber}`, 20, 50);
  pdf.text(`Date: ${invoice.createdAt.toLocaleDateString()}`, 20, 60);
  pdf.text(`Due Date: ${invoice.dueDate.toLocaleDateString()}`, 20, 70);
  
  // Billing details
  pdf.text('Bill To:', 20, 90);
  pdf.text(`${invoice.rental.name || 'N/A'}`, 20, 100);
  
  pdf.text('From:', 120, 90);
  pdf.text(`${invoice.owner.name || 'N/A'}`, 120, 100);
  
  // Machine details
  pdf.text('Machine Details:', 20, 120);
  pdf.text(`${invoice.machine.name || 'N/A'}`, 20, 130);
  
  // Amount details
  pdf.text('Amount Details:', 20, 150);
  pdf.text(`Base Amount: ₹${invoice.amount.toFixed(2)}`, 20, 160);
  pdf.text(`GST Amount: ₹${invoice.gstAmount.toFixed(2)}`, 20, 170);
  pdf.text(`Total Amount: ₹${invoice.totalAmount.toFixed(2)}`, 20, 180);
  
  // Status
  pdf.text(`Status: ${invoice.status}`, 20, 200);
  
  // Footer
  pdf.setFontSize(10);
  pdf.text('Thank you for your business!', 20, 250);
  
  // Save the PDF
  pdf.save(`invoice-${invoice.invoiceNumber}.pdf`);
};

export const generateReportPDF = (title: string, data: any[], columns: string[], generatedBy: string): void => {
  const pdf = new jsPDF();
  
  // Header
  pdf.setFontSize(16);
  pdf.setTextColor(25, 118, 210);
  pdf.text(title.toUpperCase(), 20, 30);
  
  // Report Info
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 20, 40);
  pdf.text(`Generated by: ${generatedBy}`, 20, 50);
  pdf.text(`Total Records: ${data.length}`, 20, 60);
  
  // Company Info
  pdf.setFontSize(8);
  pdf.setTextColor(100, 100, 100);
  pdf.text('Xerox Rental Management System', 20, 280);
  
  // Table headers  
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  let yPosition = 80;
  
  // Draw header background
  pdf.setFillColor(25, 118, 210);
  pdf.rect(15, yPosition - 5, 180, 10, 'F');
  
  pdf.setTextColor(255, 255, 255);
  columns.forEach((column, index) => {
    pdf.text(column, 20 + (index * 30), yPosition);
  });
  
  yPosition += 15;
  pdf.setTextColor(0, 0, 0);
  
  // Table data
  const maxRows = Math.min(data.length, 25); // Limit to prevent overflow
  
  for (let i = 0; i < maxRows; i++) {
    const row = data[i];
    
    // Alternate row colors
    if (i % 2 === 0) {
      pdf.setFillColor(245, 245, 245);
      pdf.rect(15, yPosition - 3, 180, 8, 'F');
    }
    
    columns.forEach((column, colIndex) => {
      let value = 'N/A';
      
      // Map column names to data properties
      switch (column) {
        case 'Name':
          value = row.name || 'N/A';
          break;
        case 'Email':
          value = row.email || 'N/A';
          break;
        case 'Role':
          value = row.role || 'N/A';
          break;
        case 'Contact':
          value = row.contactNumber || 'N/A';
          break;
        case 'GST Number':
          value = row.gstNumber || 'N/A';
          break;
        case 'Model':
          value = row.model || 'N/A';
          break;
        case 'Serial Number':
          value = row.serialNumber || 'N/A';
          break;
        case 'Location':
          value = row.location || 'N/A';
          break;
        case 'Status':
          value = row.status || 'N/A';
          break;
        case 'Monthly Rent':
          value = row.monthlyRent ? `₹${row.monthlyRent}` : 'N/A';
          break;
        case 'Owner':
          value = row.owner?.name || 'N/A';
          break;
        case 'Rental':
          value = row.rental?.name || 'N/A';
          break;
        case 'Machine':
          value = row.machine?.name || 'N/A';
          break;
        case 'Invoice Number':
          value = row.invoiceNumber || 'N/A';
          break;
        case 'Amount':
          value = row.totalAmount ? `₹${row.totalAmount}` : 'N/A';
          break;
        case 'Due Date':
          value = row.dueDate ? new Date(row.dueDate).toLocaleDateString() : 'N/A';
          break;
        case 'Start Date':
          value = row.startDate ? new Date(row.startDate).toLocaleDateString() : 'N/A';
          break;
        case 'End Date':
          value = row.endDate ? new Date(row.endDate).toLocaleDateString() : 'N/A';
          break;
        case 'Request Date':
          value = row.requestDate ? new Date(row.requestDate).toLocaleDateString() : 'N/A';
          break;
        case 'Created Date':
          value = row.createdAt ? new Date(row.createdAt).toLocaleDateString() : 'N/A';
          break;
        default:
          value = String(row[column.toLowerCase()] || 'N/A');
      }
      
      // Truncate long text
      const displayValue = String(value).substring(0, 12);
      pdf.text(displayValue, 20 + (colIndex * 30), yPosition);
    });
    
    yPosition += 8;
    
    // Check if we need a new page
    if (yPosition > 250) {
      pdf.addPage();
      yPosition = 30;
      
      // Repeat headers on new page
      pdf.setFillColor(25, 118, 210);
      pdf.rect(15, yPosition - 5, 180, 10, 'F');
      pdf.setTextColor(255, 255, 255);
      columns.forEach((column, index) => {
        pdf.text(column, 20 + (index * 30), yPosition);
      });
      yPosition += 15;
      pdf.setTextColor(0, 0, 0);
    }
  }
  
  // Add summary if data was truncated
  if (data.length > 25) {
    pdf.setFontSize(10);
    pdf.setTextColor(255, 0, 0);
    pdf.text(`Note: Showing first 25 records out of ${data.length} total records.`, 20, yPosition + 10);
  }
  
  // Save the PDF
  pdf.save(`${title.toLowerCase().replace(/\s+/g, '-')}-report.pdf`);
};